disabled_rules:
  - colon
  - comma
  - control_statement
  - force_cast
  - todo

opt_in_rules:
  - empty_count

excluded:
  - Pods
  - Tests

force_cast: warning
force_try: warning

line_length:
  warning: 150
  ignores_function_declarations: true
  ignores_comments: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50

identifier_name:
  min_length: 1

reporter: "junit" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
